project_identifier: liftago-mktp
api_key: d7518e59c3054336b131605cf48169e5
base_path: ./translations
preserve_hierarchy: true

files:
  -
    source: '/ride-sharing/ride-sharing.pot'
    translation: '/%original_path%/%two_letters_code%.po'
    ignore:
      - /cs
      - /pl
      - /sk
      - DriverReg
      - driver-reg
